#!/usr/local/bin/python

from path import Path

daemon = Path('/usr/local/sbin/fnxfsd')
control = Path('/usr/local/etc/init.d/fnxfsd.py')
credentials = Path('/usr/local/etc/fnxfs_credentials')

daemon.chown(0, 0)
daemon.chmod(0o700)
try:
    daemon.symlink('/sbin/mount.fnxfs')
except OSError:
    pass

credentials.chown(0, 0)
credentials.chmod(0o660)

control.chown(0, 0)
control.chmod(0o755)
control.symlink('/etc/init.d/fnxfsd.py')
control = Path('/etc/init.d/fnxfsd.py')
for shutdown in (0, 1, 6):
    control.symlink('/etc/rc.%d/K02fnxfsd' % shutdown)
for startup in (2, 3, 4, 5):
    control.symlink('/etc/rc.%d/S98fnxfsd' % startup)
