#!/usr/local/bin/suid-python
"""
This tool interacts with the FnxFS system to share files and folders with other
users.
"""
from __future__ import print_function

import sys
PYTHON_TARGET = 'python%s.%s' % sys.version_info[:2]
try:
    sys.path.remove('/usr/local/lib/%s/dist-packages' % PYTHON_TARGET)
except ValueError:
    pass
sys.path.insert(0, '/usr/local/lib/%s/dist-packages' % PYTHON_TARGET)


import os

from antipathy import Path
from errno import *
from pwd import getpwuid, getpwnam
from scription import *
from socket import socket, AF_INET, SOCK_STREAM
from VSS.utils import get_local_ip


VERSION = 'client 0.9.beta10'

HOME = Path('/home')
SHADOW = Path('/home/.shadow')
FNXFS_SHADOW = Path('/home/.fnxfs_shadow')
TARGET = None
TCP_PORT = 8068
CONFIG='/usr/local/etc/fnxfs_credentials'

AS_ROOT = False
AS_USER = getpwuid(os.getuid()).pw_name
if AS_USER == 'root':
    AS_ROOT = True
    AS_USER = None


@Script(
        as_user=('user to run command as', OPTION, None),
        config=Spec('location of configuration file', OPTION, None, Path, default=CONFIG),
        openerp=('OpenERP server to talk to', OPTION, None),
        )
def main(as_user, config, openerp):
    module.CONFIG = OrmFile(config)
    if openerp is not None:
        module.CONFIG.openerp = openerp
    module.CONFIG.local_ip = get_local_ip(module.CONFIG.openerp)
    if AS_ROOT:
        print('running as root')
    else:
        if as_user and as_user != AS_USER:
            abort('must be root to specify a different USER')
        # only allow user functions
        if module.script_command_name not in (
                'create-file', 'delete-file', 'modify',
                'create-folder', 'delete-folder', 'change-folder',
                'modify', 'show', 'sweep', 'tree',
                ):
            abort('must be root to run %r' % module.script_command_name)
        print('running as', module.AS_USER)
    module.AS_USER = as_user or AS_USER


#---------------------------
# FnxFS interaction commands
#---------------------------

@Command(
        src=Spec('/path/to/filename', type=Path, abbrev=None),
        dst=Spec('folder[/folder[/...]][/share_as_filename]', type=Path, abbrev=None),
        styp=Spec('share type', OPTION, choices=['live', 'publish', 'auto-publish'], abbrev=None, default='live'),
        ptyp=Spec('permission type', OPTION, choices=['custom', 'inherit'], abbrev=None, default='inherit'),
        ro_users=Spec('users with read-only access', MULTI, abbrev=None),
        rw_users=Spec('users with read-write access [only for "live" files]', MULTI, abbrev=None),
        desc=Spec('short description of file', OPTION, abbrev=None, default=''),
        freq=Spec('how often to republish file [only for "auto-publish" files]', OPTION, abbrev=None, default=''),
        )
def create_file(src, dst, styp, ptyp, ro_users, rw_users, desc, freq):
    "create a virtual file in the FnxFS system from a local file"
    user = AS_USER
    if user is not None:
        if src[0] != '/':
            src = '/home/%s' % user / src
        if not src.startswith(('/home/%s/' % user, '/home/.shadow/%s/' % user, '/home/.fnxfs_shadow/%s/' % user)):
            abort("can only share files from USER's home directory")
    params = ['create-file', '%s:%s' % (CONFIG.local_ip, src), dst, '--styp=%s' % styp, '--ptyp=%s' % ptyp]
    if ro_users:
        params.append('--ro-users=%s' % ','.join(ro_users))
    if rw_users:
        params.append('--rw-users=%s' % ','.join(rw_users))
    if user and user not in ro_users + rw_users:
        rw_users += (user, )
    if desc:
        params.append('--desc="%s"' % desc.replace('"', '\\"'))
    if freq:
        params.append('--freq="%s"' % freq)
    if AS_USER:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        name=Spec('name of new folder', type=Path, abbrev=None),
        styp=Spec('share type', OPTION, choices=['mirror', 'share', 'virtual'], abbrev=None, default='virtual'),
        ptyp=Spec('permission type', OPTION, choices=['custom', 'inherit'], abbrev=None, default='inherit'),
        ro_users=Spec('users with read-only access', MULTI, abbrev=None),
        rw_users=Spec('users with read-write access [only for "virtual" folders', MULTI, abbrev=None),
        cd_users=Spec('users with create/delete access [only for "virtual" folders]', MULTI, abbrev=None),
        desc=Spec('short description of folder', OPTION, abbrev=None, default=''),
        )
def create_folder(name, styp, ptyp, ro_users, rw_users, cd_users, desc):
    "create a new folder, specifying share and permission types, user access, and description"
    params = ['create-folder', name, '--styp=%s' % styp, '--ptyp=%s' % ptyp]
    user = AS_USER
    if ro_users:
        params.append('--ro-users=%s' % ','.join(ro_users))
    if rw_users:
        params.append('--rw-users=%s' % ','.join(rw_users))
    if cd_users:
        params.append('--cd-users=%s' % ','.join(cd_users))
    if user and user not in ro_users + rw_users + cd_users:
        rw_users += (user, )
    if desc:
        params.append('--desc="%s"' % desc.replace('"', '\\"'))
    if AS_USER:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        login=('user to create', ),
        level=Spec('privilege level', choices=['consumer', 'creator', 'manager'], default='consumer'),
        )
def create_user(login, level):
    "create a new user of LOGIN with LEVEL privileges"
    params = ['create-user', login, level]
    if AS_USER:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        name=('path/name of file to remove', ),
        )
def delete_file(name):
    "remove a file from FnxFS"
    params = ['delete-file', name]
    if AS_USER is not None:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        name=('path/name of file to remove', ),
        )
def delete_folder(name):
    "remove a folder from FnxFS"
    params = ['delete-folder', name]
    if AS_USER is not None:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        login=('user to delete', ),
        )
def delete_user(login):
    "remove a user from FnxFS"
    params = ['delete-user', login]
    if AS_USER is not None:
        params.append('--as-user=%s' % AS_USER)
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        name=('file/folder/user to modify', ),
        level=Spec('new privilege level for user (for users)', OPTION, choices=['consumer', 'creator', 'manager']),
        ro_users=('new list of read-only users (for files/folders)', MULTI, 'r'),
        rw_users=('new list of read-write users (for files/folders)', MULTI, 'w'),
        cd_users=('new list of read-write-create users (for folders', MULTI, 'c'), 
        del_user=('users whose access to remove (for files/folders)', MULTI),
        add_read_user=('users to add as read-only (for files/folders)', MULTI, None),
        add_write_user=('users to add as read-write (for files/folders)', MULTI, None),
        add_create_user=('users to add as read-write-create (for folders)', MULTI, None),
        )
def modify(
        name, level,
        ro_users, rw_users, cd_users,
        del_user,
        add_read_user, add_write_user, add_create_user,
        ):
    "change permissions for users, files, or folders"
    params = ['modify', name]
    if level:
        params.append('--level=%s' % level)
    if ro_users:
        params.append('--ro-users=%s' % ','.join(ro_users))
    if rw_users:
        params.append('--rw-users=%s' % ','.join(rw_users))
    if cd_users:
        params.append('--cd-users=%s' % ','.join(cd_users))
    if del_user:
        params.append('--del-user=%s' % ','.join(del_user))
    if add_read_user:
        params.append('--add-read-user=%s' % ','.join(add_read_user))
    if add_write_user:
        params.append('--add-write-user=%s' % ','.join(add_write_user))
    if add_create_user:
        params.append('--add-create-user=%s' % ','.join(add_create_user))
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command()
def refresh():
    "rewrite server permissions file from current settings"
    params = ['refresh']
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params)


@Command(
        name=Spec('name of file/folder/user to show', default=''),
        all_users=Spec('list all users', FLAG, 'u'),
        all_files=Spec('list all files', FLAG, 'f'),
        all_folders=Spec('list all folders', FLAG, 'd'),
        )
def show(name, all_users, all_files, all_folders):
    "display information about a user/file/folder"
    params = ['show']
    if name:
        params.append(name)
    if all_users:
        params.append('--all-users')
    if all_files:
        params.append('--all-files')
    if all_folders:
        params.append('--all-folders')
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params, verbose=0)


@Command(
        path=Spec('path to examine', REQUIRED, default=Path('/')),
        include_files=Spec('display files', FLAG, 'f'),
        )
def tree(path, include_files):
    "display a tree of the folder/file structure in FnxFS"
    params = ['tree', path]
    if include_files:
        params.append('--include-files')
    if script_verbosity:
        params.append('-' + 'v'*script_verbosity)
    _run(params, verbose=0)


#----------------
# fnxfsd commands
#----------------

@Command(
        user=('user to check on', ),
        )
def dump_permissions(user):
    "Query the running daemon for the permissions of the requested user."
    user = user.encode('utf8')
    server_ip = get_local_ip(CONFIG.openerp)
    s = socket(AF_INET, SOCK_STREAM)
    s.connect((server_ip, TCP_PORT))
    s.sendall('service:dump_permissions\nuser:%s' % (user, ))
    while True:
        data = s.recv(1024)
        if not data:
            break
        print(data, end='', verbose=0)
    s.close()
    print(verbose=0)


@Command(
        user=('user to check on', ),
        )
def dump_folders(user):
    "Query the running daemon for the folders of the requested user."
    user = user.encode('utf8')
    server_ip = get_local_ip(CONFIG.openerp)
    s = socket(AF_INET, SOCK_STREAM)
    s.connect((server_ip, TCP_PORT))
    s.sendall('service:dump_folders\nuser:%s' % (user, ))
    while True:
        data = s.recv(1024)
        if not data:
            break
        print(data, end='', verbose=0)
    s.close()
    print(verbose=0)


@Command(
        user=('user to check on', ),
        )
def dump_cache(user):
    "Query the running daemon for the cache of the requested user."
    user = user.encode('utf8')
    server_ip = get_local_ip(CONFIG.openerp)
    s = socket(AF_INET, SOCK_STREAM)
    s.connect((server_ip, TCP_PORT))
    s.sendall('service:dump_cache\nuser:%s' % (user, ))
    while True:
        data = s.recv(1024)
        if not data:
            break
        print(data, end='', verbose=0)
    s.close()
    print(verbose=0)


@Command(
        user=('user to check on', ),
        file_name=('file to look for', ),
        )
def find_path(user, file_name):
    "Query the running daemon for the last path that had file_name in it."
    user = user.encode('utf8')
    file_name = file_name.encode('utf8')
    print('checking user %r for %r' % (user, file_name))
    server_ip = get_local_ip(CONFIG.openerp)
    s = socket(AF_INET, SOCK_STREAM)
    s.connect((server_ip, TCP_PORT))
    s.sendall('service:find_path\nuser:%s\nfile_name:%s' % (user, file_name))
    while True:
        data = s.recv(1024)
        if not data:
            break
        print(data, end='', verbose=0)
    s.close()
    print(verbose=0)

@Command(
        level=('new log level', REQUIRED, 'l', int),
        )
def log_level(level):
    """
    Change the current logging level of fnxfsd
        10 - debug
        ...
        50 - error
    """
    s = socket(AF_INET, SOCK_STREAM)
    s.connect(('127.0.0.1', TCP_PORT))
    s.sendall('service:log_level\nlevel:%d' % (level, ))
    while True:
        data = s.recv(1024)
        if not data:
            break
        print(data, end='', verbose=0)
    s.close()
    print(verbose=0)


@Command(
    init=('overwrites existing contents in shadow directory', FLAG),
    user=('only process specified user', MULTI),
    )
def sweep(init, user):
    'moves user data (non-dot files) into a mirrored location controlled by FnxFS'
    print('looking for candidates...', end='')
    if not SHADOW.exists():
        SHADOW.mkdir()
    _squat()
    possibles = [
        p
        for p in HOME.glob('*')
        if
           p.isdir() and
           p[0] != '.' and
           p not in ('lost+found', 'backup-media') and
           (not user or p.filename in user)
        ]
    print(' found %d' % len(possibles))
    print('possibles:', possibles, verbose=2)
    for p in possibles:
        print('  checking %s...' % p)
        # create FnxFS link if not already present
        symlink = p/'FnxFS'
        if not symlink.exists():
            print('    creating symlink %s' % symlink)
            (SHADOW/p.filename/'FnxFS').symlink(symlink)
        targets = [
            t
            for t in p.listdir()
            if
                t[0] != '.' and
                not p.islink(t) and
                (p.isdir(t) or p.isfile(t))
            ]
        print('targets:', targets, verbose=2)
        user = p.filename
        for t in targets:
            src = p/t
            new_home = TARGET / user
            dst = new_home / t
            print('    moving %s to %s' % (src, dst))
            if not new_home.exists():
                st_uid, st_gid = getpwnam(user)[2:4]
                new_home.mkdir()
                new_home.chown(st_uid, st_gid)
                new_home.chmod(0755)
            try:
                src.rename(dst)
            except OSError, exc:
                if exc.errno not in (EISDIR, ENOTEMPTY):
                    raise
                if not init:
                    abort('directory %s already exists; did you mean to use --init?' % dst)
                dst.rmtree()
                src.rename(dst)
            # *always* link to SHADOW
            (SHADOW/user/t).symlink(src)


@Command(
    user=('only process specified user', OPTION),
    )
def undo_sweep(user):
    'move user data back to /home/[user]/'
    # data to move back is in TARGET
    _squat()
    possibles = [
        p
        for p in TARGET.glob('*')
        if
           p.isdir() and
           p[0] != '.' and
           p not in ('lost+found', ) and
           (user is None or p.filename == user)
        ]
    print('possibles:', possibles, verbose=2)
    problems = []
    for p in possibles:
        targets = p.listdir()
        print('targets:', targets, verbose=2)
        user = p.filename
        for t in targets:
            src = p/t
            old_home = HOME / user
            dst = old_home / t
            if dst.exists():
                if not dst.islink():
                    problems.append(dst)
                    continue
                dst.unlink()
            print('moving %s to %s' % (src, dst))
            src.rename(dst)
    if problems:
        abort('unable to move the following files/directories:\n\t%s' % '\n\t'.join(problems))


#-----------------
# private commands
#-----------------

def _run(command, verbose=1):
    params = ['ssh', '-o', 'StrictHostkeyChecking=no', 'root@'+CONFIG.openerp, '/usr/local/bin/fnxfs'] + command #+ ['-v']
    print(params)
    try:
        exc = None
        dst = stdout
        attempt = Execute(params, password=CONFIG.root, pty=True, timeout=60)
        returncode = attempt.returncode
    except ExecuteError:
        exc = sys.exc_info()[1]
        dst = stderr
        attempt = exc.process
        returncode = -1
        print(exc, 'output from command:', sep='\n', file=stderr)
    if attempt.stdout:
        print(attempt.stdout, file=dst, verbose=verbose)
    if attempt.stderr:
        print(attempt.stderr, file=stderr)
    raise SystemExit(returncode)


def _squat():
    global TARGET
    if FNXFS_SHADOW.exists():
        squatt = FNXFS_SHADOW
    else:
        squatt = SHADOW
    # make sure the directory doesn't change out from beneath our feet
    # while we are moving data around
    squatt.chdir()
    TARGET = squatt


if __name__ == "__main__":
    Run()
